name: Semgrep Code Scan

on:
  push:
    branches: [main]  # or whatever branch you're using
  pull_request:       # This enables PR annotations

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # REQUIRED for annotations in PRs

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'  # Node.js setup for your project

      - name: Install dependencies
        run: npm install

      - name: Build the app (optional)
        run: npm run build --if-present

      - name: Run Semgrep with PR Annotations
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten
