name: SAST Scan with Semgrep

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  security-events: write  # Needed for SARIF upload

jobs:
  semgrep:
    name: Run Semgrep SAST
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep with OWASP Top 10 rules
      run: semgrep --config=p/owasp-top-ten --sarif --output=semgrep.sarif

    - name: Upload SARIF to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep.sarif
